services:
  web:
    image: judge-be
    ports:
      - "8003:8001"
    depends_on:
      - db
  db:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - TZ=Asia/Seoul
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always
