# Generated by Django 3.2.9 on 2022-08-19 03:41

from django.db import migrations, models
import django.db.models.deletion
import utils.shortcuts


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem', '0001_initial'),
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.TextField(db_index=True, default=utils.shortcuts.rand_str, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.IntegerField(db_index=True)),
                ('username', models.TextField()),
                ('code', models.TextField()),
                ('result', models.IntegerField(db_index=True, default=6)),
                ('info', models.JSONField(default=dict)),
                ('language', models.TextField()),
                ('shared', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('exec_time', models.FloatField(default=0)),
                ('memory', models.BigIntegerField(default=0)),
                ('details', models.TextField(default='')),
                ('ip', models.TextField(null=True)),
                ('is_judging', models.BooleanField(default=False)),
                ('contest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.contest')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.problem')),
            ],
            options={
                'db_table': 'submission',
                'ordering': ('-create_time',),
            },
        ),
    ]
