# Generated by Django 3.2.9 on 2022-08-19 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompileRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('input', models.TextField(default='', null=True)),
                ('output', models.TextField(blank=True, null=True)),
                ('code', models.TextField()),
                ('result', models.IntegerField(db_index=True, default=6)),
                ('error', models.CharField(blank=True, max_length=140)),
                ('memory', models.BigIntegerField(default=0)),
                ('cpu_time', models.IntegerField(default=0)),
                ('real_time', models.IntegerField(default=0)),
                ('language', models.TextField()),
                ('error_message', models.TextField(blank=True, default='')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compile_run',
                'ordering': ('-created',),
            },
        ),
    ]
